- name: "Demonstrate connecting to switches"
  hosts: junos
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
    - name: Enable NETCONF
      connection: network_cli
      junos_netconf:
      when: ansible_network_os == 'junos'

#    - name: Gather facts (ops)
#      ios_facts:
#      when: ansible_network_os == 'ios'

#    - name: run show version and check to see if output contains IOS
#      ios_command:
#        commands: show version
#        wait_for: result[0] contains IOS
#
    - name: run show version and check to see if output contains Juniper
      junos_command:
        commands: show version
      connection: netconf